## Import modules

In [1]:
import pandas as pd

## Create dataframe
We'll use pothole data located [here](http://data.syrgov.net/datasets/potholes-filled)

In [5]:
potholes_filled = pd.read_csv("potholes_filled.csv")
potholes_filled.head()

,X,Y,truck_name,repair_type,date_fixed,address,activity_type,longitude,latitude,TNT_NAME,FID
0,-76.079956,43.039362,DP2,STREET REPAIR,2017-08-08T10:42:24.000Z,100 STONERIDGE DR & GENESEE S ...,Accessory On,-76.079956,43.039362,Eastside,7001
1,-76.079947,43.039452,DP2,STREET REPAIR,2017-08-08T10:47:12.000Z,101 STONERIDGE DR & GENESEE S ...,Accessory On,-76.079947,43.039452,Eastside,7002
2,-76.079875,43.039476,DP2,STREET REPAIR,2017-08-08T10:53:56.000Z,101 STONERIDGE DR & GENESEE S ...,Accessory On,-76.079875,43.039476,Eastside,7003
3,-76.079784,43.039547,DP2,STREET REPAIR,2017-08-08T10:58:03.000Z,102 STONERIDGE DR ...,Accessory On,-76.079784,43.039547,Eastside,7004
4,-76.130881,42.999335,DP2,STREET REPAIR,2017-08-11T06:47:12.000Z,154 LAFAYETTE RD ...,Accessory On,-76.130881,42.999335,Valley,7005

##Filter dataframe to only see potholes filled in the Valley

In [7]:
valley_potholes = potholes_filled[potholes_filled['TNT_NAME'] == 'Valley']
valley_potholes.head()

,X,Y,truck_name,repair_type,date_fixed,address,activity_type,longitude,latitude,TNT_NAME,FID
4,-76.130881,42.999335,DP2,STREET REPAIR,2017-08-11T06:47:12.000Z,154 LAFAYETTE RD ...,Accessory On,-76.130881,42.999335,Valley,7005
6,-76.129814,42.999723,DP2,STREET REPAIR,2017-08-11T06:48:09.000Z,139 LAFAYETTE RD SYRACUSE 13205 ...,Accessory On,-76.129814,42.999723,Valley,7007
8,-76.130788,42.999313,DP2,STREET REPAIR,2017-08-11T06:49:50.000Z,154 LAFAYETTE RD ...,Accessory On,-76.130788,42.999313,Valley,7009
10,-76.130968,42.999302,DP2,STREET REPAIR,2017-08-11T06:50:45.000Z,154 LAFAYETTE RD ...,Accessory On,-76.130968,42.999302,Valley,7011
414,-76.131176,42.997632,DP2,STREET REPAIR,2017-08-11T06:28:18.000Z,212 LAFAYETTE RD SYRACUSE 13205 ...,Accessory On,-76.131176,42.997632,Valley,7415